# Generated by Django 6.0 on 2025-12-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='productos',
            field=models.ManyToManyField(blank=True, to='notas.producto'),
        ),
    ]
