# Generated by Django 6.0 on 2025-12-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_profile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_food_set', to='notas.meal'),
        ),
    ]
