# Generated by Django 6.0 on 2025-12-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_dailyplan_is_forkable_meal_is_forkable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='owner',
            new_name='created_by',
        ),
    ]
