# Generated by Django 6.0 on 2025-12-12 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_nota_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='productos',
        ),
        migrations.CreateModel(
            name='NotaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notas.nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.producto')),
            ],
        ),
    ]
