# Generated by Django 6.0 on 2025-12-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_rename_owner_program_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_copiable',
            field=models.BooleanField(default=False),
        ),
    ]
