# Generated by Django 6.0 on 2026-01-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='pending_dailyplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notas.dailyplan'),
        ),
    ]
