# Generated by Django 6.0 on 2025-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_meal_is_copiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='is_copiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='is_copiable',
            field=models.BooleanField(default=False),
        ),
    ]
