# Generated by Django 6.0 on 2025-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_dailyplan_is_copiable_program_is_copiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
