# Generated by Django 6.0 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_dailyplanshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanshare',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
