# Generated by Django 6.0 on 2025-12-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_meal_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
