# Generated by Django 6.0 on 2025-12-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_dailyplan_is_draft_program_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
    ]
