# Generated by Django 6.0 on 2026-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_dailyplanshare_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplanshare',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
