# Generated by Django 6.0 on 2025-12-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_remove_food_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='forked_from',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='original_author',
        ),
        migrations.RemoveField(
            model_name='program',
            name='forked_from',
        ),
        migrations.RemoveField(
            model_name='program',
            name='original_author',
        ),
    ]
