# Generated by Django 6.0 on 2025-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_remove_dailyplan_forked_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplanmeal',
            name='title',
        ),
        migrations.AddField(
            model_name='dailyplanmeal',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
