# Generated by Django 6.0 on 2026-02-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_meal_alloc_carbs_cached_meal_alloc_fat_cached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='foods_aggregation_cached',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
