# Generated by Django 6.0 on 2025-12-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_remove_dailyplanmeal_title_dailyplanmeal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplanmeal',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
