# Generated by Django 6.0 on 2026-04-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0013_backfill_mealfood_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
