import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notas", "0020_mcpusertoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=160,
                    ),
                ),
                (
                    "redirect_uris",
                    models.JSONField(
                        default=list,
                    ),
                ),
                (
                    "allowed_scopes",
                    models.JSONField(
                        default=list,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "client_name",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthAuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uri",
                    models.URLField(
                        max_length=500,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                    ),
                ),
                (
                    "code_challenge",
                    models.CharField(
                        max_length=160,
                    ),
                ),
                (
                    "code_challenge_method",
                    models.CharField(
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="notas.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-created_at",
                    "-id",
                ],
            },
        ),
    ]