# Generated by Django 6.0 on 2026-05-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_oauthclient_oauthauthorizationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('applied', 'applied')], default='pending_review', max_length=30),
        ),
    ]
