# Generated by Django 6.0 on 2026-05-14 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0022_alter_nutritionproposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Imported source. Example: usda, open_food_facts, latinfoods.', max_length=50)),
                ('source_version', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Food import batch',
                'verbose_name_plural': 'Food import batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='canonical_name',
            field=models.CharField(blank=True, help_text='Normalized name for search, deduplication and external sources.', max_length=255),
        ),
        migrations.AddField(
            model_name='food',
            name='data_quality_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Internal data quality score from 0 to 100.'),
        ),
        migrations.AddField(
            model_name='food',
            name='default_portion_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Suggested default portion in grams.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fiber in grams per 100 g.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_group',
            field=models.CharField(blank=True, help_text='General nutritional/category group. Example: cereals, meats, legumes.', max_length=120),
        ),
        migrations.AddField(
            model_name='food',
            name='food_subgroup',
            field=models.CharField(blank=True, help_text='Optional nutritional/category subgroup.', max_length=120),
        ),
        migrations.AddField(
            model_name='food',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Allows hiding foods without deleting them.'),
        ),
        migrations.AddField(
            model_name='food',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates whether this food has been reviewed or approved for reliable use.'),
        ),
        migrations.AddField(
            model_name='food',
            name='max_portion_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Suggested maximum portion for future optimization.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='min_portion_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Suggested minimum portion for future optimization.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='portion_step_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Suggested portion increment step.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Saturated fat in grams per 100 g.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium_mg_per_100g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sodium in milligrams per 100 g.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar_g_per_100g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sugar in grams per 100 g.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='visibility',
            field=models.CharField(choices=[('core', 'Core'), ('extended', 'Extended'), ('hidden', 'Hidden'), ('rejected', 'Rejected')], default='extended', help_text='Food visibility level in search and catalogs.', max_length=30),
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Portion name. Example: 1 large egg, 1 cup, 1 tablespoon.', max_length=120)),
                ('grams', models.DecimalField(decimal_places=3, help_text='Portion equivalent in grams.', max_digits=8)),
                ('source', models.CharField(blank=True, help_text='Portion source: manual, usda, open_food_facts, etc.', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='notas.food')),
            ],
            options={
                'verbose_name': 'Food portion',
                'verbose_name_plural': 'Food portions',
                'ordering': ['food', '-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alternative food name or search alias.', max_length=255)),
                ('normalized_name', models.CharField(blank=True, help_text='Normalized alias for search.', max_length=255)),
                ('language', models.CharField(default='es', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Optional country code. Example: CL, AR, MX.', max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='notas.food')),
            ],
            options={
                'verbose_name': 'Food alias',
                'verbose_name_plural': 'Food aliases',
                'ordering': ['food', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('normalized_name', ''), _negated=True), fields=('food', 'normalized_name', 'language', 'country'), name='unique_food_alias_per_language_country')],
            },
        ),
        migrations.CreateModel(
            name='FoodSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('usda', 'USDA FoodData Central'), ('open_food_facts', 'Open Food Facts'), ('latinfoods', 'LATINFOODS'), ('inta_chile', 'INTA Chile'), ('admin_import', 'Admin import')], default='manual', max_length=50)),
                ('source_food_id', models.CharField(blank=True, help_text='Food ID in the external source.', max_length=120)),
                ('source_dataset', models.CharField(blank=True, help_text='Specific dataset inside the source.', max_length=120)),
                ('source_version', models.CharField(blank=True, help_text='Source dataset version.', max_length=120)),
                ('source_url', models.URLField(blank=True, help_text='Reference URL for the original source.')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last date this food was compared or synchronized with its source.', null=True)),
                ('raw_payload_hash', models.CharField(blank=True, help_text='Hash of the original imported payload.', max_length=128)),
                ('normalized_payload_hash', models.CharField(blank=True, help_text='Hash of the normalized payload used by My Scoope.', max_length=128)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('attribution', models.TextField(blank=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_metadata', to='notas.food')),
            ],
            options={
                'verbose_name': 'Food source metadata',
                'verbose_name_plural': 'Food source metadata',
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_food_id', ''), _negated=True), fields=('source', 'source_food_id'), name='unique_food_source_external_id')],
            },
        ),
    ]
