# Generated by Django 6.0 on 2026-05-16 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0023_foodimportbatch_food_canonical_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLocalizedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Localized display name for this food.', max_length=255)),
                ('normalized_name', models.CharField(blank=True, help_text='Normalized localized name for search and deduplication.', max_length=255)),
                ('language', models.CharField(default='es', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Optional country code. Example: CL, AR, MX.', max_length=10)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary localized name for this language/country.')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_names', to='notas.food')),
            ],
            options={
                'verbose_name': 'Food localized name',
                'verbose_name_plural': 'Food localized names',
                'ordering': ['food', 'language', 'country', '-is_primary', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('normalized_name', ''), _negated=True), fields=('food', 'normalized_name', 'language', 'country'), name='unique_food_localized_name_per_language_country')],
            },
        ),
    ]
